<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-2336HU1" failures="4" tests="15" name="Regression Test" time="151.593" errors="0" timestamp="2023-03-01T20:32:42 TRT">
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="13.257">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="13.641">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="15.182">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="13.922">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="3.073"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.204"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="1.467"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="1.091"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="1.081"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.872"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.34"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.335"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.346"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.352"/>
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.346"/>
  <testcase classname="com.exelenter.testcases.AddEmployeeTest" name="addEmployeeTest" time="0.0">
    <ignored/>
  </testcase> <!-- addEmployeeTest -->
</testsuite> <!-- Regression Test -->
